services:
  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/config:/etc/prometheus
      - ./docker/prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - metrics

  loki:
    image: grafana/loki
    container_name: loki
    hostname: loki
    restart: unless-stopped
    ports:
      - 3100:3100
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - metrics
    depends_on:
      - prometheus
      - loki

networks:
  metrics:
    driver: bridge
